export const countries_list = [
  { name: 'Albania', continent: 'europe' },
  { name: 'Andorra', continent: 'europe' },
  { name: 'Australia', continent: 'oceania' },
  { name: 'Brazil', continent: 'south_america' },
  { name: 'Belgium', continent: 'europe' },
  { name: 'Canada', continent: 'north_america' },
  { name: 'China', continent: 'asia' },
  { name: 'France', continent: 'europe' },
  { name: 'Germany', continent: 'europe' },
  { name: 'India', continent: 'asia' },
  { name: 'Indonesia', continent: 'asia' },
  { name: 'Ireland', continent: 'europe' },
  { name: 'Italy', continent: 'europe' },
  { name: 'Japan', continent: 'asia' },
  { name: 'Kenya', continent: 'africa' },
  { name: 'Luxembourg', continent: 'europe' },
  { name: 'Mexico', continent: 'north_america' },
  { name: 'New Zealand', continent: 'oceania' },
  { name: 'Nigeria', continent: 'africa' },
  { name: 'Portugal', continent: 'europe' },
  { name: 'Russia', continent: 'europe' },
  { name: 'South Africa', continent: 'africa' },
  { name: 'South Korea', continent: 'asia' },
  { name: 'Spain', continent: 'europe' },
  { name: 'Sweden', continent: 'europe' },
  { name: 'Thailand', continent: 'asia' },
  { name: 'Ukraine', continent: 'europe' },
  { name: 'United Kingdom', continent: 'europe' },
  { name: 'United States of America', continent: 'north_america' },
  { name: 'Vietnam', continent: 'asia' },
  { name: 'Zambia', continent: 'africa' },
];